# Generated by Django 4.1.7 on 2023-10-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white')], max_length=50, verbose_name='Цвет')),
                ('style', models.CharField(choices=[('classic', 'classic'), ('modern', 'modern')], max_length=50, verbose_name='Стиль кухни')),
                ('material', models.CharField(choices=[('PVX', 'PVX'), ('LDSP', 'LDSP'), ('MDF', 'MDF')], max_length=50, verbose_name='Материал кухни')),
                ('form', models.CharField(choices=[('straight', 'straight'), ('angular', 'angular'), ('narrow', 'narrow')], max_length=50, verbose_name='Форма кухни')),
                ('width', models.ImageField(upload_to='', verbose_name='Ширина кухни')),
            ],
        ),
    ]
