# Generated by Django 4.1.7 on 2023-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_kitchen_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='color',
            field=models.CharField(choices=[('black', 'Черный'), ('white', 'Белый')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='form',
            field=models.CharField(choices=[('straight', 'Прямой'), ('angular', 'Угловой'), ('narrow', 'Узкий')], max_length=50, verbose_name='Форма кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='material',
            field=models.CharField(choices=[('PVX', 'ПВХ'), ('LDSP', 'ЛДСП'), ('MDF', 'МДФ')], max_length=50, verbose_name='Материал кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='style',
            field=models.CharField(choices=[('classic', 'Классический'), ('modern', 'Модерн')], max_length=50, verbose_name='Стиль кухни'),
        ),
    ]
