# Generated by Django 4.1.7 on 2023-10-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kitchen_color_alter_kitchen_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Стиль кухни',
                'verbose_name_plural': 'Стили кухни',
            },
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'Кухня', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='color',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='form',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='width',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KitchenOpeningMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('kitchen_styles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitchenstyle', verbose_name='Вид кухни')),
            ],
            options={
                'verbose_name': 'Способ открытия',
                'verbose_name_plural': 'Способы открытия',
            },
        ),
        migrations.CreateModel(
            name='KitchenMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('kitchen_styles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitchenstyle', verbose_name='Вид кухни')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='openingMethod',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.kitchenopeningmethod', verbose_name='Метод открытия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitchenmaterial', verbose_name='Материал кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='main.kitchenstyle', verbose_name='Вид кухни'),
        ),
    ]
