# Generated by Django 4.2.6 on 2023-10-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kitchenstyle_alter_kitchen_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'блок о нас',
                'verbose_name_plural': 'Блок о нас',
            },
        ),
        migrations.CreateModel(
            name='AboutUsDopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подпись')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Маленький блок в блоке о нас',
                'verbose_name_plural': 'Дополнительные значения в блоке о нас',
            },
        ),
        migrations.CreateModel(
            name='KitchenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchen/', verbose_name='Фото кухни')),
            ],
            options={
                'verbose_name': 'фотографию кухни',
                'verbose_name_plural': 'Фотографии кухонь',
            },
        ),
        migrations.CreateModel(
            name='MainPageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кухни')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Фото кухни')),
                ('show_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'кухню',
                'verbose_name_plural': 'Кухни в карусели на главной странице',
            },
        ),
        migrations.CreateModel(
            name='ReviewsAndProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review/', verbose_name='Фото')),
                ('project_name', models.CharField(max_length=50, verbose_name='Название кухни')),
                ('price', models.IntegerField(verbose_name='Стоимость проекта')),
                ('squeare', models.IntegerField(verbose_name='Площадь кухни')),
                ('review_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'кухню', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.AlterModelOptions(
            name='kitchenmaterial',
            options={'verbose_name': 'материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='kitchenopeningmethod',
            options={'verbose_name': 'cпособ открытия', 'verbose_name_plural': 'Способы открытия'},
        ),
        migrations.AlterModelOptions(
            name='kitchenstyle',
            options={'verbose_name': 'стиль кухни', 'verbose_name_plural': 'Стили кухни'},
        ),
        migrations.AddField(
            model_name='kitchen',
            name='mainImage',
            field=models.ImageField(default=123, upload_to='kitchen/', verbose_name='Главное фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='openingMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitchenopeningmethod', verbose_name='Метод открытия кухни'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.kitchenphoto', verbose_name='Дополнительные фотографии кухни'),
        ),
    ]
