# Generated by Django 4.2.6 on 2023-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutus_aboutusdopblock_kitchenphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='show_number',
            field=models.IntegerField(null=True, verbose_name='Номер показа в карусели каталога'),
        ),
    ]
