# Generated by Django 4.2.6 on 2023-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kitchen_show_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='short_desc',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание для карусели каталога'),
        ),
    ]
