# Generated by Django 4.2.6 on 2023-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kitchen_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='short_desc',
            field=models.CharField(default=0, max_length=300, verbose_name='Краткое описание для карусели каталога'),
            preserve_default=False,
        ),
    ]
