# Generated by Django 4.2.6 on 2023-11-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_kitchen_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание для карусели каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='show_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер показа в карусели каталога'),
        ),
    ]
