# Generated by Django 4.2.6 on 2023-11-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_kitchen_short_desc_alter_kitchen_show_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
