# Generated by Django 4.2.6 on 2023-11-10 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_kitchen_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='KitchenColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование цвета')),
                ('image', models.ImageField(upload_to='kitchen/colors/', verbose_name='Фото цвета')),
            ],
            options={
                'verbose_name': 'цвет кухни',
                'verbose_name_plural': 'Цвета кухонь',
            },
        ),
        migrations.CreateModel(
            name='KitchenFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('files', models.FileField(upload_to='kitchen/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'файл кухни',
                'verbose_name_plural': 'Файлы кухонь',
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.FileField(default=1232, upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для каталога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='desc',
            field=models.TextField(default=123, verbose_name='Описание для страницы кухни'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.FileField(default=123, upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для страницы кухни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='images',
            field=models.ManyToManyField(to='main.kitchenphoto', verbose_name='Дополнительные фотографии кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='short_desc',
            field=models.CharField(max_length=300, verbose_name='Краткое описание для карусели каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='KitchenFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование отделки')),
                ('colors', models.ManyToManyField(blank=True, to='main.kitchencolors', verbose_name='Цвета кухни')),
            ],
            options={
                'verbose_name': 'отделку кухни',
                'verbose_name_plural': 'Отделки кухонь',
            },
        ),
        migrations.AddField(
            model_name='kitchen',
            name='files',
            field=models.ManyToManyField(to='main.kitchenfiles', verbose_name='Файлы кухни'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='finishing',
            field=models.ManyToManyField(to='main.kitchenfinishing', verbose_name='Отделка кухни'),
        ),
    ]
