# Generated by Django 4.2.6 on 2023-11-08 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedback_kitchen_catalogvideo_alter_kitchen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.FileField(upload_to='kitchen/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для каталога'),
        ),
    ]
