# Generated by Django 4.2.6 on 2023-11-08 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedback_kitchen_catalogvideo_alter_kitchen_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='kitchen/colors/', verbose_name='Фото цвета')),
            ],
            options={
                'verbose_name': 'цвет кухни',
                'verbose_name_plural': 'Цвета кухонь',
            },
        ),
        migrations.CreateModel(
            name='KitchenFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('files', models.FileField(upload_to='kitchen/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'файл кухни',
                'verbose_name_plural': 'Файлы кухонь',
            },
        ),
        migrations.CreateModel(
            name='KitchenFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'отделку кухни',
                'verbose_name_plural': 'Отделки кухонь',
            },
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.FileField(upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для каталога'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='colors',
            field=models.ManyToManyField(blank=True, to='main.kitchencolors', verbose_name='Цвета кухни'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.kitchenfiles', verbose_name='Файлы кухни'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='finishing',
            field=models.ManyToManyField(blank=True, to='main.kitchenfinishing', verbose_name='Отделка кухни'),
        ),
    ]
