# Generated by Django 4.2.6 on 2023-11-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_kitchencolors_kitchenfiles_kitchenfinishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание для страницы кухни'),
        ),
    ]
