# Generated by Django 4.2.6 on 2023-11-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_kitchen_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='desc',
            field=models.TextField(verbose_name='Описание для страницы кухни'),
        ),
    ]
