# Generated by Django 4.2.6 on 2023-11-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_feedback_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
    ]
