# Generated by Django 4.2.6 on 2023-11-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_kitchen_catalogvideo'),
        ('main', '0014_alter_kitchen_desc'),
    ]

    operations = [
    ]
