# Generated by Django 4.2.6 on 2023-11-09 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20231109_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='colors',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.FileField(default=123, upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для страницы кухни'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchenfinishing',
            name='colors',
            field=models.ManyToManyField(blank=True, to='main.kitchencolors', verbose_name='Цвета кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.FileField(upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео для каталога'),
        ),
        migrations.AlterField(
            model_name='kitchencolors',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование цвета'),
        ),
        migrations.AlterField(
            model_name='kitchenfinishing',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование отделки'),
        ),
    ]
