# Generated by Django 4.2.6 on 2023-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_lookat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookat',
            name='image',
            field=models.FileField(help_text='png, jpg, gif', upload_to='look_at/', verbose_name='Фото или видео'),
        ),
    ]
