# Generated by Django 4.2.6 on 2023-11-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_lookat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookat',
            name='is_play',
        ),
        migrations.AlterField(
            model_name='lookat',
            name='image',
            field=models.FileField(help_text='png, jpg, webp, mp4, webm', upload_to='look_at/', verbose_name='Фото или видео'),
        ),
    ]
