# Generated by Django 4.2.6 on 2023-11-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_lookat_is_play_alter_lookat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookat',
            old_name='image',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lookat',
            old_name='video_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='lookat',
            old_name='video_name',
            new_name='name',
        ),
    ]
