# Generated by Django 4.2.6 on 2023-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_image_lookat_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookat',
            name='show_number',
            field=models.IntegerField(default=0, verbose_name='Номер показа'),
        ),
    ]
