# Generated by Django 4.2.6 on 2023-11-17 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_kitchen_material_remove_kitchen_openingmethod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'основную информацию «О нас»', 'verbose_name_plural': 'Основная информация «О нас»'},
        ),
        migrations.AlterModelOptions(
            name='aboutusdopblock',
            options={'verbose_name': 'О нас в цифрах', 'verbose_name_plural': 'О нас в цифрах '},
        ),
        migrations.AlterModelOptions(
            name='mainpagecarousel',
            options={'verbose_name': 'кухню', 'verbose_name_plural': 'Карусель кухонь на первом экране'},
        ),
        migrations.AlterModelOptions(
            name='reviewsandproject',
            options={'verbose_name': 'наш проект', 'verbose_name_plural': 'Наши проекты'},
        ),
        migrations.RemoveField(
            model_name='kitchenmaterial',
            name='kitchen_styles',
        ),
        migrations.RemoveField(
            model_name='kitchenopeningmethod',
            name='kitchen_styles',
        ),
        migrations.AddField(
            model_name='aboutusdopblock',
            name='show_number',
            field=models.IntegerField(default=1, help_text='Объекты отображаются в порядке возрастания (слева направо)', verbose_name='Номер показа '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(help_text='Доступные форматы: jpg, png, webp', upload_to='about/', verbose_name='Главное фото в блоке «О нас»'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(help_text='Обратите внимание - учитываются отступы и знаки переноса', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutusdopblock',
            name='name',
            field=models.CharField(help_text='Пример: «сделано в Италии»', max_length=50, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='aboutusdopblock',
            name='value',
            field=models.CharField(help_text='Укажите число, включая единицы измерения. Например, 100%', max_length=50, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.FileField(help_text='Проигрывается на странице каталога при наведении курсора на изображение кухни. Доступные форматы: mp4, webm', upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Видео для каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='desc',
            field=models.TextField(help_text='Отображается в карточке кухни. Обратите внимание - учитываются отступы и знаки переноса', verbose_name='Описание для страницы кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='files',
            field=models.ManyToManyField(help_text='Загрузите не более трех файлов в формате PDF. Присваиваете файлам корректные имена, например, «Техническое описание.pdf»', to='main.kitchenfiles', verbose_name='PDF-файлы'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='finishing',
            field=models.ManyToManyField(help_text='Выберите одну или несколько отделок кухни', to='main.kitchenfinishing', verbose_name='Отделка кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='images',
            field=models.ManyToManyField(help_text='Объекты отображаются в порядке их добавления', to='main.kitchenphoto', verbose_name='Дополнительные фотографии кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.FileField(help_text='Отображается в карточке кухни. Доступные форматы: mp4, webm', upload_to='kitchen/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm'])], verbose_name='Видео для карточки кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='mainImage',
            field=models.ImageField(help_text='Отображается: 1) на главное странице в блоке «Каталог»; 2) на странице каталога', upload_to='kitchen/', verbose_name='Главное фото кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='material',
            field=models.ManyToManyField(help_text='Выберите один или несколько материалов', to='main.kitchenmaterial', verbose_name='Материал кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(help_text='Пример: «Stosa Young»', max_length=50, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='openingMethod',
            field=models.ManyToManyField(help_text='Выберите один или несколько методов открытия кухни', to='main.kitchenopeningmethod', verbose_name='Метод открытия кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='show_number',
            field=models.IntegerField(blank=True, help_text='Объекты отображаются в порядке возрастания', null=True, verbose_name='Номер показа в карусели каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='style',
            field=models.ForeignKey(help_text='«Любой» - означает, что кухня одновременно относится к классическому и современному стилю', on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='main.kitchenstyle', verbose_name='Стиль кухни'),
        ),
        migrations.AlterField(
            model_name='kitchencolors',
            name='image',
            field=models.ImageField(help_text='Фотография плитки цвета. Доступные форматы: jpg, png, webp', upload_to='kitchen/colors/', verbose_name='Фото цвета'),
        ),
        migrations.AlterField(
            model_name='kitchencolors',
            name='name',
            field=models.CharField(help_text='Введите наименование цвета', max_length=50, verbose_name='Наименование цвета'),
        ),
        migrations.AlterField(
            model_name='kitchenfinishing',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Выберите один или несколько цветов, которые соответствуют данной отделке', to='main.kitchencolors', verbose_name='Цвета кухни'),
        ),
        migrations.AlterField(
            model_name='kitchenfinishing',
            name='name',
            field=models.CharField(help_text='Пример: «Дубовая древесина»', max_length=50, verbose_name='Введите наименование отделки'),
        ),
        migrations.AlterField(
            model_name='kitchenmaterial',
            name='name',
            field=models.CharField(help_text='Пример: «Лакированный»', max_length=50, verbose_name='Введите материал кухни'),
        ),
        migrations.AlterField(
            model_name='kitchenopeningmethod',
            name='name',
            field=models.CharField(help_text='Пример: «Ручка Pocket»', max_length=50, verbose_name='Введите способ открытия'),
        ),
        migrations.AlterField(
            model_name='kitchenstyle',
            name='name',
            field=models.CharField(help_text='Пример: «Классический стиль»', max_length=50, verbose_name='Введите стиль кухни'),
        ),
        migrations.AlterField(
            model_name='lookat',
            name='content',
            field=models.FileField(help_text='Доступные форматы: jpg, png, webp, mp4, webm', upload_to='look_at/', verbose_name='Фото или видео'),
        ),
        migrations.AlterField(
            model_name='lookat',
            name='name',
            field=models.CharField(help_text='Обратите внимание - учитывается регистр введенных символов', max_length=50, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='lookat',
            name='show_number',
            field=models.IntegerField(default=0, help_text='Объекты отображаются в порядке возрастания', verbose_name='Номер показа'),
        ),
        migrations.AlterField(
            model_name='mainpagecarousel',
            name='image',
            field=models.ImageField(help_text='Доступные форматы: jpg, png, webp', upload_to='carousel/', verbose_name='Фото кухни'),
        ),
        migrations.AlterField(
            model_name='mainpagecarousel',
            name='name',
            field=models.CharField(help_text='Пример: «Stosa Young»', max_length=50, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='mainpagecarousel',
            name='show_number',
            field=models.IntegerField(help_text='Объекты отображаются в порядке возрастания', verbose_name='Номер показа в карусели '),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='image',
            field=models.ImageField(help_text='Доступные форматы: jpg, png, webp', upload_to='review/', verbose_name='Главная фотография проекта'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='price',
            field=models.IntegerField(help_text='Введите стоимость проекта в евро', verbose_name='Стоимость проекта'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='project_name',
            field=models.CharField(help_text='Пример: «Stosa Young»', max_length=50, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='review_name',
            field=models.CharField(help_text='Пример: «Иванов Иван»', max_length=100, verbose_name='Фамилия и имя заказчика'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='squeare',
            field=models.IntegerField(help_text='Введите площадь проекта в квадратных метрах', verbose_name='Площадь проекта'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='text',
            field=models.TextField(help_text='Обратите внимание - учитываются отступы и знаки переноса', verbose_name='Текст отзыва'),
        ),
    ]
