# Generated by Django 4.2.6 on 2023-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_aboutus_options_alter_aboutusdopblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='catalogVideoUrl',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.CharField(help_text='Проигрывается на странице каталога при наведении курсора на изображение кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=50, verbose_name='Видео для каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.CharField(help_text='Отображается в карточке кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=50, verbose_name='Видео для карточки кухни'),
        ),
    ]
