# Generated by Django 4.2.6 on 2023-11-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_kitchen_catalogvideourl_alter_kitchen_catalogvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='catalogVideoUrl',
        ),
        migrations.AddField(
            model_name='lookat',
            name='shorts',
            field=models.CharField(blank=True, help_text='Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, null=True, verbose_name='Ссылка на полное видео'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.CharField(help_text='Проигрывается на странице каталога при наведении курсора на изображение кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, verbose_name='Видео для каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.CharField(help_text='Отображается в карточке кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, verbose_name='Видео для карточки кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(help_text='Пример: «Young»', max_length=50, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='lookat',
            name='content',
            field=models.FileField(help_text='Доступные форматы: webp, mp4', upload_to='look_at/', verbose_name='Фото или видео'),
        ),
    ]
