# Generated by Django 4.2.6 on 2023-11-24 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_kitchen_catalogvideourl_lookat_shorts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politucFile', models.FileField(upload_to='politic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
