# Generated by Django 4.2.6 on 2023-11-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_politic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecarousel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainpagecarousel',
            name='name',
            field=models.CharField(help_text='Пример: «Young»', max_length=50, verbose_name='Название кухни'),
        ),
    ]
