# Generated by Django 4.2.6 on 2023-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_mainpagecarousel_slug_alter_mainpagecarousel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politic',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'Файл политики обработки персональных данных'},
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='catalogVideo',
            field=models.CharField(blank=True, help_text='Проигрывается на странице каталога при наведении курсора на изображение кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, null=True, verbose_name='Видео для каталога'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.CharField(help_text='Отображается в карточке кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, verbose_name='Видео или фото для карточки кухни'),
        ),
        migrations.AlterField(
            model_name='kitchenfiles',
            name='name',
            field=models.CharField(help_text='Например: «City. Техническое описание»', max_length=100, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='lookat',
            name='content',
            field=models.FileField(help_text='Доступные форматы: webp, jpg, png, mp4', upload_to='look_at/', verbose_name='Фото или видео'),
        ),
    ]
