# Generated by Django 4.2.6 on 2023-11-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_politic_options_alter_kitchen_catalogvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='kitchenCardPhoto',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp', null=True, upload_to='kitchen/card/', verbose_name='Фото для карточки кухни'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideo',
            field=models.CharField(blank=True, help_text='Отображается в карточке кухни. Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, null=True, verbose_name='Видео для карточки кухни'),
        ),
    ]
