# Generated by Django 4.2.6 on 2023-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_kitchen_kitchencardphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='kitchenCardVideoPhotoChoices',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], default=123, max_length=50, verbose_name='Выбирите видео или фото'),
            preserve_default=False,
        ),
    ]
