# Generated by Django 4.2.6 on 2023-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_kitchen_kitchencardvideophotochoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: «Компетентность»', max_length=50, verbose_name='Наименование абзаца')),
                ('text', models.TextField(verbose_name='Текст абзаца')),
                ('show_number', models.IntegerField(default=0, help_text='Объекты отображаются в порядке возрастания', verbose_name='Номер показа')),
            ],
            options={
                'verbose_name': 'приемущества',
                'verbose_name_plural': 'Текст в блоке «Приемущества»',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOne', models.CharField(blank=True, help_text='Пример: «Дизайн и качество»', max_length=50, null=True, verbose_name='Заголовок 1 уровня')),
                ('titleTwo', models.CharField(help_text='Пример: «Взгляните сами»', max_length=50, verbose_name='Заголовок 2 уровня')),
            ],
            options={
                'verbose_name': 'приемущества',
                'verbose_name_plural': 'Заголовки блока «Приемущества»',
            },
        ),
        migrations.CreateModel(
            name='FeedbackBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пример: «Заказать персональную консультацию»', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст подписи')),
                ('image', models.ImageField(help_text='Доступные форматы: jpg, png, webp', upload_to='contact/', verbose_name='Фоновая фотография')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'Блок контакты',
            },
        ),
        migrations.CreateModel(
            name='LookAtTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOne', models.CharField(blank=True, help_text='Пример: «Дизайн и качество»', max_length=50, null=True, verbose_name='Заголовок 1 уровня')),
                ('titleTwo', models.CharField(help_text='Пример: «Взгляните сами»', max_length=50, verbose_name='Заголовок 2 уровня')),
            ],
            options={
                'verbose_name': 'взгляни сам',
                'verbose_name_plural': 'Заголовки блока «Взгляните сами»',
            },
        ),
        migrations.CreateModel(
            name='ReviewsAndProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пример: «Наши проекты и отзывы»', max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'наш проект',
                'verbose_name_plural': 'Заголовки блока «Наши проекты»',
            },
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchenCardVideoPhotoChoices',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], help_text='Обязательно выберите фото или введите ссылку на видео в блоке ниже', max_length=50, verbose_name='Выбирите видео или фото для карточки кухни'),
        ),
        migrations.AlterField(
            model_name='kitchenfiles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='review_name',
            field=models.CharField(blank=True, help_text='Пример: «Иванов Иван»', max_length=100, null=True, verbose_name='Фамилия и имя заказчика'),
        ),
        migrations.AlterField(
            model_name='reviewsandproject',
            name='text',
            field=models.TextField(blank=True, help_text='Обратите внимание - учитываются отступы и знаки переноса', null=True, verbose_name='Текст отзыва'),
        ),
    ]
