# Generated by Django 4.2.6 on 2023-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_advantagesblocks_advantagestitle_feedbackblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=123, help_text='Пример: «О нас»', max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantagestitle',
            name='titleOne',
            field=models.CharField(blank=True, help_text='Пример: «Преимущества»', max_length=50, null=True, verbose_name='Заголовок 1 уровня'),
        ),
        migrations.AlterField(
            model_name='advantagestitle',
            name='titleTwo',
            field=models.CharField(help_text='Пример: «Почему нас выбирают»', max_length=50, verbose_name='Заголовок 2 уровня'),
        ),
    ]
