# Generated by Django 4.2.6 on 2023-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_aboutus_title_alter_advantagestitle_titleone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchVideoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, null=True, verbose_name='Видео для кнопки «Смотреть видео» на главной странице')),
            ],
            options={
                'verbose_name': 'приемущества',
                'verbose_name_plural': 'Текст в блоке «Приемущества»',
            },
        ),
    ]
