# Generated by Django 4.2.6 on 2023-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_watchvideomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchvideomain',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'Ссылка на видео для кнопки «Смотреть видео» на главной странице'},
        ),
        migrations.AddField(
            model_name='kitchen',
            name='hide',
            field=models.BooleanField(default=False, help_text='Для скрытия поставьте галочку', verbose_name='Скрыть'),
        ),
        migrations.AddField(
            model_name='lookat',
            name='hide',
            field=models.BooleanField(default=False, help_text='Для скрытия поставьте галочку', verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='watchvideomain',
            name='url',
            field=models.CharField(blank=True, help_text='Например: https://www.youtube.com/watch?v=z8xoGi5pK70', max_length=100, null=True, verbose_name='Ссылка на видео для кнопки «Смотреть видео» на главной странице'),
        ),
    ]
