# Generated by Django 4.2.6 on 2023-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_watchvideomain_options_kitchen_hide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: «Каталог кухонь»', max_length=50, verbose_name='Наименование раздела')),
                ('text', models.TextField(verbose_name='Текст абзаца')),
            ],
            options={
                'verbose_name': 'надпись',
                'verbose_name_plural': 'Надписи в каталоге',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: «CERTIFICAZIONE ISO 9001:2015»', max_length=50, verbose_name='Наименование сертификата')),
                ('image', models.ImageField(help_text='Доступные форматы: jpg, png, webp', upload_to='certificate/', verbose_name='Фотограия сертификата')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'Сертификаты в карточке кухни',
            },
        ),
    ]
