# Generated by Django 4.2.6 on 2023-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_catalogtitle_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogtitle',
            name='text',
            field=models.TextField(verbose_name='Подпись'),
        ),
    ]
