# Generated by Django 4.2.6 on 2023-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_catalogtitle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantagesblocks',
            name='text',
            field=models.TextField(max_length=150, verbose_name='Текст абзаца'),
        ),
        migrations.AlterField(
            model_name='catalogtitle',
            name='text',
            field=models.CharField(help_text='Пример: «Мы делаем не просто кухни, мы создаём стиль»', max_length=100, verbose_name='Подпись'),
        ),
    ]
