# Generated by Django 4.2.6 on 2023-12-12 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_aboutus_fontsize_alter_advantagesblocks_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='alignmentH',
            field=models.CharField(choices=[('center', 'Фото'), ('left', 'Видео'), ('end', 'Видео')], default=1, max_length=300, verbose_name='Выравнивание заголовка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alignmentText',
            field=models.CharField(choices=[('center', 'Фото'), ('left', 'Видео'), ('end', 'Видео')], default=12, max_length=300, verbose_name='Выравнивание текста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='fontsizeH',
            field=models.IntegerField(default=1, help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='fontsize',
            field=models.IntegerField(help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер текста в блоке'),
        ),
    ]
