# Generated by Django 4.2.6 on 2023-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_aboutus_alignmenth_aboutus_alignmenttext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='fontsize',
            new_name='fontsizeText',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='alignmentH',
            field=models.CharField(choices=[('center', 'По центру'), ('left', 'По левому краю'), ('end', 'По правому краю')], max_length=300, verbose_name='Выравнивание заголовка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='alignmentText',
            field=models.CharField(choices=[('center', 'По центру'), ('left', 'По левому краю'), ('end', 'По правому краю')], max_length=300, verbose_name='Выравнивание текста'),
        ),
    ]
