# Generated by Django 4.2.6 on 2023-12-18 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_fontsize_aboutus_fontsizetext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontsize', models.IntegerField(help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер текста кнопки')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Кнопка «Смотреть все кухни» на главной странице',
            },
        ),
        migrations.AlterModelOptions(
            name='watchvideomain',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'Кнопка «Смотреть видео» на главной странице'},
        ),
        migrations.AddField(
            model_name='watchvideomain',
            name='fontsize',
            field=models.IntegerField(default=123, help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер текста кнопки'),
            preserve_default=False,
        ),
    ]
