# Generated by Django 4.2.6 on 2023-12-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_advantagestitle_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantagestitle',
            old_name='fontsixeH',
            new_name='fontsizeH',
        ),
        migrations.RenameField(
            model_name='advantagestitle',
            old_name='fontsixeText',
            new_name='fontsizeText',
        ),
        migrations.RenameField(
            model_name='advantagestitle',
            old_name='fontsixeTextH',
            new_name='fontsizeTextH',
        ),
    ]
