# Generated by Django 4.2.6 on 2023-12-20 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_catalogtitle_fontsizefilter_catalogtitle_fontsizeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackblock',
            name='fontsize',
            field=models.IntegerField(default=16, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackblock',
            name='fontsizeText',
            field=models.IntegerField(default=32, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер текста подписи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackblock',
            name='fontsizeTiteTwo',
            field=models.IntegerField(default=32, help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка абзаца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackblock',
            name='titleTwo',
            field=models.CharField(default=32, help_text='Пример: «Контакты»', max_length=50, verbose_name='Заголовок 2 уровня'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='title',
            field=models.CharField(help_text='Пример: «Заказать персональную консультацию»', max_length=50, verbose_name='Заголовок 1 уровня'),
        ),
    ]
