# Generated by Django 4.2.6 on 2023-12-21 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_feedbackblock_fontsize_feedbackblock_fontsizetext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogtitle',
            name='fontsize404',
            field=models.IntegerField(default=12, help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер черной надписи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogtitle',
            name='fontsize404Gray',
            field=models.IntegerField(default=12, help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер серой надписи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogtitle',
            name='name404',
            field=models.CharField(default=12, help_text='Пример: «К сожалению, ничего не найдено»', max_length=50, verbose_name='Надпись черного цвета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogtitle',
            name='name404Gray',
            field=models.CharField(default=12, help_text='Пример: «Попробуйте изменить критерии поиска»', max_length=50, verbose_name='Надпись серого цвета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogtitle',
            name='fontsizeText',
            field=models.IntegerField(help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер подписи заголовка'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='fontsizeTiteTwo',
            field=models.IntegerField(help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка 2 уровня'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='title',
            field=models.CharField(help_text='Пример: «Контакты»', max_length=50, verbose_name='Заголовок 1 уровня'),
        ),
    ]
