# Generated by Django 4.2.6 on 2023-12-21 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_kitchencardtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchencardtext',
            name='colorMaterialName',
            field=models.CharField(default=12, help_text='Пример: «Цвет и отделка»', max_length=50, verbose_name='Заголовок блока с материалами'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchencardtext',
            name='fontsizeColorMaterial',
            field=models.IntegerField(help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка блока с материалами'),
        ),
    ]
