# Generated by Django 4.2.6 on 2023-12-21 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_kitchencardtext_colormaterialname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogmain',
            options={'verbose_name': 'надпись', 'verbose_name_plural': 'Кнопка «Смотреть все кухни» на главной странице'},
        ),
        migrations.AddField(
            model_name='feedbackblock',
            name='fontsizeBtn',
            field=models.IntegerField(default=12, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер подписи кнопки "Оставить заявку"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchencardtext',
            name='fontsizeBtn',
            field=models.IntegerField(default=12, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер подписи кнопки "Оставить заявку"'),
            preserve_default=False,
        ),
    ]
