# Generated by Django 4.2.6 on 2023-12-21 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_catalogmain_options_feedbackblock_fontsizebtn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пример: «Выберите идеальную кухню для вас»', max_length=50, verbose_name='Заголовок 1 уровня')),
                ('fontsize', models.IntegerField(help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня')),
                ('titleTwo', models.CharField(help_text='Пример: «Каталог»', max_length=50, verbose_name='Заголовок 2 уровня')),
                ('fontsizeTiteTwo', models.IntegerField(help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка 2 уровня')),
            ],
            options={
                'verbose_name': 'надпись',
                'verbose_name_plural': "Надписи в блоке 'Каталог'",
            },
        ),
    ]
