# Generated by Django 4.2.6 on 2023-12-21 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_feedbackblock_fontsizeinput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleLookAt', models.CharField(help_text='Пример: «Взгляните сами»', max_length=50, verbose_name='Надпись для перехода в блок «Взгляните сами»')),
                ('titleMore', models.CharField(help_text='Пример: «Больше возможностей»', max_length=50, verbose_name='Надпись для перехода в блок «Больше возможностей»')),
                ('titleCatalog', models.CharField(help_text='Пример: «Контакты»', max_length=50, verbose_name='Надпись для перехода в блок «Контакты»')),
                ('fontsize', models.IntegerField(help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер надписей')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'Блок контакты',
            },
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='inputMassage',
            field=models.CharField(help_text='Например: «Сообщение»', max_length=50, verbose_name='Надпись для ввода сообщения'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='inputName',
            field=models.CharField(help_text='Например: «Имя (обязательно)»', max_length=50, verbose_name='Надпись для ввода имени'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='inputPhone',
            field=models.CharField(help_text='Например: «Телефон (обязательно)»', max_length=50, verbose_name='Надпись для ввода телефона'),
        ),
    ]
