# Generated by Django 4.2.6 on 2023-12-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_footer_alter_header_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='titleContact',
            field=models.CharField(default=123, help_text='Пример: «Контакты»', max_length=50, verbose_name='Надпись для перехода в блок «Контакты»'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='header',
            name='titleCatalog',
            field=models.CharField(help_text='Пример: «Каталог»', max_length=50, verbose_name='Надпись для перехода в каталог'),
        ),
    ]
