# Generated by Django 4.2.6 on 2023-12-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_header_titlecontact_alter_header_titlecatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='titleContact',
            field=models.CharField(default=123, help_text='Пример: «Контакты»', max_length=50, verbose_name='Надпись для перехода в блок «Контакты»'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='titleCatalog',
            field=models.CharField(help_text='Пример: «Каталог»', max_length=50, verbose_name='Надпись для перехода в каталог'),
        ),
    ]
