# Generated by Django 4.2.6 on 2023-12-25 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_footer_titlecontact_alter_footer_titlecatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, help_text='Обратите внимание - учитываются отступы и знаки переноса', null=True, verbose_name='Текст отзыва')),
                ('image1', models.ImageField(help_text='Доступные форматы: jpg, png, webp. Отображается в первой строке', upload_to='more/', verbose_name='Фотография 1')),
                ('image2', models.ImageField(help_text='Доступные форматы: jpg, png, webp. Отображается во второй строке слева', upload_to='more/', verbose_name='Фотография 2')),
                ('image3', models.ImageField(help_text='Доступные форматы: jpg, png, webp. Отображается во второй строке справа', upload_to='more/', verbose_name='Фотография 3')),
                ('showNumber', models.IntegerField(blank=True, help_text='Объекты отображаются в порядке возрастания', null=True, verbose_name='Номер показа в карусели')),
            ],
            options={
                'verbose_name': 'наш проект',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
        migrations.CreateModel(
            name='MoreMainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Пример: «Дизайн»', max_length=50, verbose_name='Заголовок 1 уровня')),
                ('fontsize', models.IntegerField(help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня')),
                ('titleTwo', models.CharField(help_text='Пример: «Больше возможностей»', max_length=50, verbose_name='Заголовок 2 уровня')),
                ('fontsizeTiteTwo', models.IntegerField(help_text='Размер от 16 до 36', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(36)], verbose_name='Размер заголовка 2 уровня')),
                ('fontsizeTiteText', models.IntegerField(help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка текста в слайде')),
                ('fontsizeText', models.IntegerField(help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер текста в слайде')),
            ],
            options={
                'verbose_name': 'надпись',
                'verbose_name_plural': 'Надписи в блоке «Больше возсожностей»',
            },
        ),
        migrations.DeleteModel(
            name='ReviewsAndProject',
        ),
        migrations.DeleteModel(
            name='ReviewsAndProjectTitle',
        ),
        migrations.AlterModelOptions(
            name='catalogmainblock',
            options={'verbose_name': 'надпись', 'verbose_name_plural': 'Надписи в блоке «Каталог»'},
        ),
    ]
