# Generated by Django 4.2.6 on 2023-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_moreblocks_moremainblock_delete_reviewsandproject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreblocks',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'Слайды в блоке «Больше возможностей»'},
        ),
        migrations.AlterModelOptions(
            name='moremainblock',
            options={'verbose_name': 'надпись', 'verbose_name_plural': 'Надписи в блоке «Больше возможностей»'},
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='text',
            field=models.TextField(blank=True, help_text='Обратите внимание - учитываются отступы и знаки переноса', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
