# Generated by Django 4.2.6 on 2023-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_moreblocks_options_alter_moremainblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreblocks',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
