# Generated by Django 4.2.6 on 2023-12-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_moreblocks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreblocks',
            name='title',
            field=models.CharField(default=12, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moremainblock',
            name='title',
            field=models.CharField(help_text='Пример: «Дизайн»', max_length=50, null=True, verbose_name='Заголовок 1 уровня'),
        ),
    ]
