# Generated by Django 4.2.6 on 2023-12-27 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_moreblocks_title_alter_moremainblock_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='advantages1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Поле 1'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='advantages2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Поле 2'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='advantages3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Поле 3'),
        ),
        migrations.AlterField(
            model_name='catalogmainblock',
            name='fontsize',
            field=models.IntegerField(default=14, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня'),
        ),
        migrations.AlterField(
            model_name='catalogmainblock',
            name='title',
            field=models.CharField(blank=True, help_text='Пример: «Выберите идеальную кухню для вас»', max_length=50, null=True, verbose_name='Заголовок 1 уровня'),
        ),
        migrations.AlterField(
            model_name='catalogtitle',
            name='text',
            field=models.TextField(help_text='Пример: «Мы делаем не просто кухни, мы создаём стиль»', verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='fontsize',
            field=models.IntegerField(default=14, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня'),
        ),
        migrations.AlterField(
            model_name='feedbackblock',
            name='title',
            field=models.CharField(blank=True, help_text='Пример: «Контакты»', max_length=50, null=True, verbose_name='Заголовок 1 уровня'),
        ),
        migrations.AlterField(
            model_name='moremainblock',
            name='fontsize',
            field=models.IntegerField(default=14, help_text='Размер от 14 до 22', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(22)], verbose_name='Размер заголовка 1 уровня'),
        ),
        migrations.AlterField(
            model_name='moremainblock',
            name='title',
            field=models.CharField(blank=True, help_text='Пример: «Дизайн»', max_length=50, null=True, verbose_name='Заголовок 1 уровня'),
        ),
    ]
