# Generated by Django 4.2.6 on 2024-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_delete_aboutusdopblock_catalogmainblock_kitchentitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreblocks',
            name='image4',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp', null=True, upload_to='more/', verbose_name='Фотография 4'),
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image1',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp', null=True, upload_to='more/', verbose_name='Фотография 1'),
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image2',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp', null=True, upload_to='more/', verbose_name='Фотография 2'),
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image3',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp', null=True, upload_to='more/', verbose_name='Фотография 3'),
        ),
    ]
