# Generated by Django 4.2.6 on 2024-02-05 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_moreblocks_image4_alter_moreblocks_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchencardtext',
            name='fontsizeNextKitchen',
            field=models.IntegerField(default=14, help_text='Размер от 14 до 24', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(24)], verbose_name='Размер подписи для перехода к следующей кухни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image1',
            field=models.ImageField(default=1, help_text='Доступные форматы: jpg, png, webp', upload_to='more/', verbose_name='Фотография 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image2',
            field=models.ImageField(default=1, help_text='Доступные форматы: jpg, png, webp', upload_to='more/', verbose_name='Фотография 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image3',
            field=models.ImageField(default=1, help_text='Доступные форматы: jpg, png, webp', upload_to='more/', verbose_name='Фотография 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moreblocks',
            name='image4',
            field=models.ImageField(blank=True, help_text='Доступные форматы: jpg, png, webp. Может быть не выбрана', null=True, upload_to='more/', verbose_name='Фотография 4'),
        ),
    ]
